



AWSTemplateFormatVersion: '2010-09-09'
Description: Stack that sets up an example custom action for removing 0.0.0.0/0 from security groups
Parameters:
  ModuleName:
    Type: String
    Default: "index"
Resources:
  CustomEventRule:
    Type: AWS::Events::Rule
    Name:
    Properties: 
      Description: Eventbridge rule for 0.0.0.0/0 
      EventBusName: "default"
      EventPattern: {
          "source": ["aws.securityhub"],
          "detail-type": ["Security Hub Findings - Custom Action"],
          "resources": ["arn:aws:securityhub:us-east-1:899456967600:action/custom/dev001"]
      }
      RoleArn: String

      State: String
      Targets: 
        - Target


  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Path: "/"
        Policies:
          -
            PolicyName: "SGPermissions"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action: 
                  - "ec2:RevokeSecurityGroupIngress",
                    "ec2:DescribeSecurityGroupRules",
                    "ec2:RevokeSecurityGroupEgress",
                    "ec2:DescribeSecurityGroups"
                  Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: customaction_remove_sg_0rule
      Description: Lambda function used to remove a 0 rule from a security group
      Code:

      Handler: !Sub "${ModuleName}.handler"
      Runtime: python3.9
      Timeout: 300
      Role: !GetAtt LambdaRole.Arn
      Environment: 
        Variables:
          RuleValue: "0.0.0.0/0"

Outputs:
  LambdaArn:

